spring.application.name=building-calculation-backend


spring.datasource.url=jdbc:postgresql://localhost:5432/building_calculation
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080